export {
  DURATION_OPTIONS,
  MIN_DURATION_MINUTES,
  MAX_DURATION_MINUTES,
  GRACE_PERIOD_MS,
  TIMER_INTERVAL_MS,
  STATE_RESET_DELAY_MS,
  TREE_STAGES,
  STORAGE_KEYS,
  COLORS,
} from './timer';
export type { TreeStage } from './timer';
